name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions üöÄ
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout AWS RUM Web Client Repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
            node-version: '16.x'
            registry-url: 'https://registry.npmjs.org'

      - name: List files in the repository
        run: |
         npm i npm-run-all -D
         echo "1"
          ls ${{ github.workspace }}
          pwd 
          cd app
          echo "2"
          ls
          pwd
          
      - run: |
          echo "üçè This job's status is ${{ job.status }}."
          npm run release 
        

